### ISSUE TITLE
What to do in times of UIStackView?

### ISSUE THREAD

**Issue by buk** [mamaral/Facade#11]
Hey @mamaral 

how are you? I just stumbled upon your Project and it looks really cool. But Apple announced `UIStackView` and i am asking myself what the advantage is, using Facaded in comparisson to Apples Solution.

**Comment by mamaral** [comment]
I've looked into the UIStackView docs, and still find this a more clear and concise. I'd be interested to see how one would implement something like my demo screenshot in the README using UIStackView, and how that compares to using Façade. My guess is UIStackView would take quite a bit more code and/or work if using IB. I honestly don't know though, I haven't used it yet - could be awesome.
