### ISSUE TITLE
Using it in UITableViewCell

### ISSUE THREAD

**Issue by danglade** [mamaral/Facade#23]
Hello,

Love your project. Can I use this category in a UITableViewCell?

**Comment by mamaral** [comment]
Yes, you can use it in any `UIView`, just put your layout code in `layoutSubviews`.

**Comment by danglade** [comment]
Thank you! Will try it!

**Comment by mamaral** [comment]
No problem, LMK if you have issues!

**Comment by danglade** [comment]
Maybe I'm doing something wrong when reusing the cells, but I don't think so. Look at the behavior of the cells.

Look at this video -> https://www.dropbox.com/s/uc9jqdpmvofom4v/Untitled.mov?dl=0

Let me know,

Thanks

```
#import "TableViewController.h"
#import "Cell.h"
#import "UIView+Facade.h"

@interface TableViewController ()
{
    UILabel *_label;;

}

@end

@implementation TableViewController

- (void)viewDidLoad {
    [super viewDidLoad];

    // Uncomment the following line to preserve selection between presentations.
    // self.clearsSelectionOnViewWillAppear = NO;

    // Uncomment the following line to display an Edit button in the navigation bar for this view controller.
    // self.navigationItem.rightBarButtonItem = self.editButtonItem;
}

- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
    // Dispose of any resources that can be recreated.
}

- (void)viewWillLayoutSubviews {
    [super viewWillLayoutSubviews];

    [self layoutFacade];
}

- (void)layoutFacade {

    [_label anchorTopRightWithRightPadding:10 topPadding:10 width:110 height:20];

}

#pragma mark - Table view data source

- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath*)indexPath;
{
    return 200;

    }

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    return 1;
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return 10;
}


- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {


    static NSString *cellIdentifier = @"cell";
    Cell * cell = [tableView dequeueReusableCellWithIdentifier:cellIdentifier];
    if (!cell) {
        cell = [[Cell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:cellIdentifier];
    }

        cell.userInteractionEnabled = YES;
        _label = [UILabel new];
        [_label sizeToFit];
        _label.font = [UIFont systemFontOfSize:24];
        _label.text = @"Pruebaaa";
        [cell addSubview:_label];

        // Configure the cell...
        cell.selectionStyle = UITableViewCellSelectionStyleBlue;
        cell.backgroundColor = [UIColor colorWithRed:0.957 green:0.957 blue:0.957 alpha:1] /*#f4f4f4*/;


                return cell;
}
```

**Comment by mamaral** [comment]
I'm reading this on a phone at the moment so not 100% sure, but it looks like your adding 1 instance of a label as a subview to multiple cells.

**Comment by danglade** [comment]
Correct, and it won't show that label until I scroll the view. Which is weird.

If I do cell.textlabel.text it will show at the beginning with no scrolling needed.

**Comment by mamaral** [comment]
Yeah the problem has nothing to do with Facade or the layout, it has to do with cell reuse. You cant have the same view as a subview of multiple views. Each cell needs its own instance of that label.

**Comment by danglade** [comment]
I understand, what would be the best practice here to use Facade on a UITableViewCell?

**Comment by mamaral** [comment]
Subclass UITableViewCell, put a label in there, and in that cell's layoutSubviews method is where you would have your Facade code.

**Comment by mamaral** [comment]
In one of my open source apps, I have a UICollectionViewCell I do this with. You can reference the source here:

https://github.com/mamaral/xkcd-Open-Source/blob/master/Source/Views/Comic%20Cell/ComicCell.m

**Comment by danglade** [comment]
I will check it out! 

Thank you man!
