### ISSUE TITLE
Rounded UIImageView not showing

### ISSUE THREAD

**Issue by danglade** [mamaral/Facade#24]
Hello,

I'm using 

```
    self.imagerView = [UIImageView new];
    self.imagerView.layer.cornerRadius = self.imagerView.frame.size.width / 2;
    self.imagerView.clipsToBounds = YES;
    [self.containerView addSubview:self.imagerView];
```

and

```
[self.imagerView anchorTopLeftWithLeftPadding:10 topPadding:10 width:50 height:50];
```

But UIimageView is not rounding as expected.

Please advise.

**Comment by mamaral** [comment]
Facade should have nothing to do with the rounding of the image view, all it does it set the frame.

**Comment by mamaral** [comment]
Looking at your code the problem is likely that the image view has no frame when you create it, so you're setting the radius to 0. Try setting the corner radius after you set the frame using facade.

**Comment by danglade** [comment]
Awesome man.

**Comment by mamaral** [comment]
Did that fix it for you?

**Comment by danglade** [comment]
Yes! I did.

**Comment by mamaral** [comment]
Awesome, glad to help.
