### ISSUE TITLE
Animations of a group or a view

### ISSUE THREAD

**Issue by guyisra** [mamaral/Facade#3]
Is it possible to apply animations to a group as a whole, and/or apply an animation block to a group such that each view inside will use it? 

Or all views should just be treated regularly?

**Comment by mamaral** [comment]
Can you give me an example of what you mean?

**Comment by guyisra** [comment]
take the vertical social bar as an example

if the icons are grouped vertically, I might want to animate the entire thing as a whole to slide from the right. Or I would animate each one to slide on its own.

Is Facade just better syntax for autolayout or does it affect in any way on how the view behaves if its in a group?

**Comment by mamaral** [comment]
In a nutshell, the UIView+Facade category is just a collection on convenience methods that set the frames of views based on their superview and/or sibling views. Take the vertical grouping in the upper-right corner for a simple example:

``` objective-c
- (void)groupVertically:(NSArray *)subviews inUpperRightWithRightPadding:(CGFloat)right topPadding:(CGFloat)top spacing:(CGFloat)spacing width:(CGFloat)width height:(CGFloat)height {
    CGFloat yOrigin = top;

    for (UIView *view in subviews) {
        view.frame = CGRectMake(CGRectGetWidth(self.frame) - width - right, yOrigin, width, height);

        yOrigin += height + spacing;
    }
}
```

That's all it does under the covers, there's no actual auto-layout anywhere in the code. I would imagine you'd be able to simply wrap any Facade API's in a UIView `animateWithDuration:animations:` call, and all of the frames _should_ animate properly.

**Comment by mamaral** [comment]
I just tried that out and it seemed to work fine... Here's the original setup code:

``` objective-c
    [_redView anchorInCenterFillingWidthAndHeightWithLeftAndRightPadding:10 topAndBottomPadding:10];
    [_redView groupVertically:@[_orangeView, _yellowView, _greenView] inUpperRightWithRightPadding:7 topPadding:7 spacing:7 width:50 height:50];
```

When I clicked the button here's the method I called:

``` objective-c
- (void)testAnimate {
    [UIView animateWithDuration:2 animations:^{
        [_redView groupVertically:@[_orangeView, _yellowView, _greenView] inUpperLeftWithLeftPadding:7 topPadding:7 spacing:7 width:50 height:50];
    }];
}
```

...and here was the result:

https://dl.dropboxusercontent.com/u/142773735/animate-example.mov

**Comment by guyisra** [comment]
ok, great, thanks!
